name = "bageri-leve"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-02-13"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
