name = "bageri-leve"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-02-13"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
